dataset_path: ''
audio_path: ''
label_path: D:/label/aihub_labels.csv
model_path: ''

print_interval: 10
num_vocabs: 2000
pad_id: 0
sos_id: 1
eos_id: 2
blank_id: 1999

batch_size: 4
num_workers: 4
cuda: True
seed: 22
mode: eval
