extension: pcm
sampling_rate: 16000
n_mfcc: 40
frame_length: 0.020
frame_stride: 0.010
feature_extraction: mfcc
normalize: False
spec_augment: True
num_time_mask: 1
num_freq_mask: 1 
freq_mask_parameter: 8
