extension: pcm
sampling_rate: 16000
frame_length: 20
frame_stride: 10
n_mel: 0
feature_extraction: spectrogram
normalize: True
spec_augment: True
num_time_mask: 1
num_freq_mask: 1
freq_mask_parameter: 24